name: Deploy aws stack on git push
permissions:
  id-token: write
  contents: read
on:
  push:
    branches: [github_workflow]
jobs:
  Deploy:
    name: Deploy aws stack
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: AlphabeticalAnomaly/DailyTestCDK


    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Deploy LambdaStack (via CDK)
      uses: youyo/aws-cdk-github-actions@v2
      with:
         cdk_subcommand: 'deploy'
         cdk_stack: './dailymail/dailymail_stack.py'
         cdk_args: '--require-approval never'
         actions_comment: false
