name: Deploy aws stack on git push
on:
  push:
    branches: [github_workflow]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Clean global cache
        run: npm cache clean --force
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
            node-version: '18'
        working-directory: './DAILYMAIL'
      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
            cdk_subcommand: 'deploy'
            cdk_stack: 'dailymail_stack'
            cdk_args: '--require-approval never'
            actions_comment: false
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
