name: Deploy aws stack on git push
on:
  push:
    branches: [github_workflow]
jobs:
  Deploy:
    name: Deploy aws stack
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: AlphabeticalAnomaly/DailyTestCDK
    - name: SetUp Node.js env
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: nmp
    - name: Install root dependencies
      run: nmp ci
    - name: Install dependencies
      working-directory: ./DAILYMAIL
      run: nmp ci
    - name: Install CDK
      run: nmp i -g aws-cdk

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: AWS login
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Deploy stack
      working-directory: ./DAILYMAIL
      run: cdk deploy --app --require-approval never
