name: Deploy aws stack on git push
on:
  push:
    branches: [github_workflow]
jobs:
  Deploy:
    name: Deploy aws stack
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
#    - name: cdk diff
#      uses: youyo/aws-cdk-github-actions@v2
#      with:
#        cdk_subcommand: 'diff'
#        actions_comment: true
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        AWS_DEFAULT_REGION: eu-north-1
    - name: cdk deploy
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'deploy'
        cdk_stack: 'DailymailStack'
        cdk_args: '--require-approval never'
        actions_comment: false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-north-1

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: AlphabeticalAnomaly/DailyTestCDK

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: AWS login
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Deployment
      id: cdk-deploy
      run:
        cdk deploy --parameters email= ${{ secrets.AWS_EMAIL }}
        y



